version: 0.2
# buildspec for gradle build 
phases:
  install:
    commands:
     # variables


  pre_build:
    commands:

  build:
    commands:
      #- echo Maven Build ...
      #- mvn package
      - echo Gradle Build
      - chmod +x gradlew
      - ./gradlew build
      

  post_build:
    commands:

       
artifacts:
     #files:  target/spring-boot.jar
     files: build/libs/ungerw-spring-boot-docker-0.0.1-SNAPSHOT.jar